In [2]:
### import any dataset for csv spam classification
import pandas as pd
messages = pd.read_csv(r'C:\Users\krish\Downloads\spam.csv', sep="\t", names=["label", "message"])
messages

label                                            message
0    Type                                            Message
1     ham  Go until jurong point, crazy.. Available only ...
2     ham                      Ok lar... Joking wif u oni...
3    spam  Free entry in 2 a wkly comp to win FA Cup fina...
4     ham  U dun say so early hor... U c already then say...
..    ...                                                ...
652   ham                  Anything lor. Juz both of us lor.
653   ham  Get me out of this dump heap. My mom decided t...
654   ham  Ok lor... Sony ericsson salesman... I ask shuh...
655   ham                                Ard 6 like dat lor.
656   ham  Why don't you wait 'til at least wednesday to ...

[657 rows x 2 columns]

In [6]:
import re
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review= [lemma.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=" ".join(review)
    corpus.append(review)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=200)
X= tfidf.fit_transform(corpus).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
tfidf.vocabulary_

{'message': np.int64(99),
 'go': np.int64(53),
 'point': np.int64(127),
 'great': np.int64(58),
 'got': np.int64(57),
 'wat': np.int64(182),
 'ok': np.int64(117),
 'lar': np.int64(77),
 'free': np.int64(46),
 'comp': np.int64(26),
 'win': np.int64(189),
 'text': np.int64(159),
 'txt': np.int64(173),
 'rate': np.int64(132),
 'dun': np.int64(37),
 'say': np.int64(138),
 'already': np.int64(1),
 'think': np.int64(163),
 'life': np.int64(87),
 'hey': np.int64(66),
 'week': np.int64(184),
 'word': np.int64(191),
 'back': np.int64(11),
 'like': np.int64(88),
 'still': np.int64(152),
 'xxx': np.int64(196),
 'send': np.int64(141),
 'even': np.int64(40),
 'per': np.int64(120),
 'set': np.int64(144),
 'friend': np.int64(47),
 'customer': np.int64(30),
 'prize': np.int64(129),
 'claim': np.int64(20),
 'call': np.int64(15),
 'hour': np.int64(70),
 'mobile': np.int64(102),
 'month': np.int64(104),
 'latest': np.int64(81),
 'camera': np.int64(16),
 'co': np.int64(22),
 'home': np.int64(68),
 'soon':