In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentence
sent=[ "the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "i am a developer",
      "understand the meaning of words",
      "your videos are good"

]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'i am a developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4652, 613, 9082, 5631],
 [4652, 613, 9082, 3330],
 [4652, 8062, 9082, 3532],
 [6387, 5425, 5778, 9040, 7534],
 [6387, 5425, 5778, 1602],
 [3717, 4652, 3602, 9082, 3586],
 [4945, 1102, 3989, 9040]]

In [6]:
## Word Embedding Representation

import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
## Pre is used to add zeroes at the beginning and Post is used to add zeroes at the end
print(embedded_docs)

[[   0    0    0    0 4652  613 9082 5631]
 [   0    0    0    0 4652  613 9082 3330]
 [   0    0    0    0 4652 8062 9082 3532]
 [   0    0    0 6387 5425 5778 9040 7534]
 [   0    0    0    0 6387 5425 5778 1602]
 [   0    0    0 3717 4652 3602 9082 3586]
 [   0    0    0    0 4945 1102 3989 9040]]


In [10]:
### Feature Representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\code\Python\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step


array([[[ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.01345137,  0.03700818, -0.00285297, -0.03146731,
         -0.01209704,  0.0461374 , -0.04498342,  0.01002345,
          0.04747726,  0.04176629],
        [ 0.00119399,  0.03558684, -0.04989338, -0.01004828,
          0.00660592,  0.04408484, -0.01178395, -0.04920936,
         -0.01163397, -0.03805806],
        [ 0.04297458,  0.01189159, -0.0050053 , -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4652,  613, 9082, 5631])

In [18]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.04668584,  0.01886242, -0.04400178, -0.04621819,
         -0.02814158, -0.02596132,  0.02865079,  0.0103706 ,
          0.04089031,  0.03408051],
        [ 0.01345137,  0.03700818, -0.00285297, -0.03146731,
         -0.01209704,  0.0461374 , -0.04498342,  0.01002345,
          0.04747726,  0.04176629],
        [ 0.00119399,  0.03558684, -0.04989338, -0.01004828,
          0.00660592,  0.04408484, -0.01178395, -0.04920936,
         -0.01163397, -0.03805806],
        [ 0.04297458,  0.01189159, -0.0050053 , -0.0